FILES=`{ls | grep -v mkfile}

default:VQ:
	echo mk all, mk install, mk uninstall

all clean nuke:QV:
	echo -n

install:V: ${FILES:%=%.install}

%.install:V:
	cp -x $stem /rc/bin/$stem

uninstall:QV: ${FILES:%=%.uninstall}

%.uninstall:V:
	rm -f /rc/bin/$stem
