.TH CHAT 1
.SH NAME
chat \- internet relay chat client
.SH SYNOPSIS
.B chat
[
.B -t
] [
.B -a
.I address
]
.SH DESCRIPTION
.I Chat
is an
.B IRC
client. By default, it connects to
chat.freenode.net at port at port 6667
or the server specified in the
.B $irc
environment variable (see
.IR dial (2))
and reads raw
.B IRC
commands from standard input. Chat recognizes the following flags:
.TP
.B -t
Connect using TLS.
.TP
.B -a
Set the address to
.I address.
.PP
.I Chat
also recognizes the following control
messages:
.TP
.B /q \fItarget\fR
This opens a new window that relays
messages to the
.I target.
The
.I target
can be a channel or a nick.
The created window
also accepts control messages.
.TP
.BI /x
Closes a window and parts. If sent to
the main window, the connection is closed
and the program exits.
.TP
.B /n \fIdoofus\fR
Change nicknames to
.I doofus.
.SH EXAMPLES
Join #cat-v and then open a private
message window with glenda:
.br
.ne 3
.IP
.EX
chat
/q #cat-v
/q glenda
.EE
.SH SOURCE
https://github.com/mischief/plan9
.SH SEE ALSO
.IR ircrc (1)
