</$objtype/mkfile

BIN=/$objtype/bin
TARG=chat
OFILES=\
	main.$O\
	util.$O\
	wind.$O\

LIB=/$objtype/lib/libirc.a

MAN=/sys/man/1

</sys/src/cmd/mkone

install:V:	man

uninstall:V:
	rm -f $BIN/$TARG $MAN/$TARG
